Remember/urls.py
from django.conf.urls import include, url

from .views import *
import django.conf.urls

app_name = 'Remember'
urlpatterns = [
    url(r'^hello$', foo, name='hello'), 
    url(r'^$', index, name='index'),
    url(r'^logout$', logout_view, name='logout'),
    url(r'^signup$', SignUpView.as_view(), name='signup'),
    url(r'^login', LoginView.as_view(), name='login'),
    url(r'^profile', ProfileView.as_view(), name='profile'),
    url('^calendar$', CalendarView.as_view(), name='calendar'),
    url('^dashboard$', dashboard, name='dashboard'),
    url('^task/', include([
        url('^new/$', TaskCreateView.as_view(), name='task_new'),
        url('(?P<task_id>\d+)/', include([
            url('^details/$', task_details, name='task_details'),
            url('^edit/', include([
                url('^$', TaskUpdateView.as_view(), name='task_edit'),
                url('^complex$', edit_task_complex, name='task_edit_complex'),
                url('^notification/', include([
                    url('(?P<notification_id>\d+)', NotificationUpdateView.as_view(), name='notification_edit'),
                    url('new$', NotificationCreateView.as_view(), name='notification_new')
                ])),
                url('repeat/', include([
                    url('create$', RepeatCreateView.as_view(), name='repeat_new'),
                    url('edit', RepeatUpdateView.as_view(), name='repeat_edit'),
                    url('add_exclusion', ExclusionCreateView.as_view(), name='exclusion_add')
                ])),
                url('^connection/', include([
                    url('subtask/(?P<user_username>.+)/edit', SubConnectionUpdateView.as_view(), name='subtask_edit'),
                    url('subtask/(?P<user_username>.+)$', SubConnectionCreateView.as_view(), name='subtask'),
                    url('create/(?P<user_username>[a-zA-Z0-9]+)$', ConnectionCreateView.as_view(), name='connection_new'),
                    url('create/(?P<user_username>.+)/(?P<receiver_id>\d+)', ConnectionUpdateView.as_view(),
                        name='connection_edit'),
                ])),
            ])),
        ])),
    ]))
]


django.conf.urls.handler404 = 'Remember.views.handler404'
django.conf.urls.handler500 = 'Remember.views.handler500'
django.conf.urls.handler403 = 'Remember.views.handler403'
django.conf.urls.handler400 = 'Remember.views.handler400'

TaskTracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import reverse
from django.views.generic import RedirectView

urlpatterns = [
    url(r'remember/', include('Remember.urls'), name='remember'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='remember/', permanent=False))
]

Remember/models/dashboard.py
import django.contrib.auth.models as auth_models
from django.db import models

from ..config import CHOICES_FIELD_MAX_LENGTH, MAX_TEXT_FIELD_LENGTH


class Dashboard(models.Model):
    NOTIFICATION_REASON_SHORT = 'N'
    ASSIGN_REASON_SHORT = 'A'
    TIME_LIMIT_REASON_SHORT = 'T'

    REASONS = (
        (NOTIFICATION_REASON_SHORT, 'Notification'),
        (ASSIGN_REASON_SHORT, 'Assign'),
        (TIME_LIMIT_REASON_SHORT, 'Time limit')
    )

    user = models.ForeignKey(auth_models.User, on_delete=models.CASCADE)
    text = models.CharField(max_length=MAX_TEXT_FIELD_LENGTH)
    reason = models.CharField(max_length=CHOICES_FIELD_MAX_LENGTH, choices=REASONS)
    datetime = models.DateTimeField(auto_now_add=True)

Remember/models/notification.py
from dateutil.relativedelta import relativedelta
from django.db import models

from .dashboard import Dashboard
from .task import Task
from .. import consts
from ..config import CHOICES_FIELD_MAX_LENGTH, MAX_TEXT_FIELD_LENGTH


class Notification(models.Model):
    EMAIL_SUBJECT = 'Remember! notification'
    __CHOICES_LENGTH = 1
    DEFAULT_TEXT = 'Task {task_name} hit the notification time.'
    EMAIL_TARGET_SHORT = consts.NOTIFICATION_EMAIL_TARGET[:__CHOICES_LENGTH]
    DASHBOARD_TARGET_SHORT = consts.NOTIFICATION_DASHBOARD_TARGET[:__CHOICES_LENGTH]
    TARGETS = (
        (EMAIL_TARGET_SHORT, consts.NOTIFICATION_EMAIL_TARGET),
        (DASHBOARD_TARGET_SHORT, consts.NOTIFICATION_DASHBOARD_TARGET)
    )
    ABSOLUTE_SHORT = consts.ABSOLUTE_TIME_TYPE[:__CHOICES_LENGTH]
    RELATIVE_SHORT = 'R'

    __TIME_TYPES = (
        (ABSOLUTE_SHORT, consts.ABSOLUTE_TIME_TYPE),
        (RELATIVE_SHORT, consts.RELATIVE_TIME_TYPE)
    )

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    copy_of = models.ForeignKey('Notification',
                                on_delete=models.CASCADE,
                                related_name='copies',
                                null=True)
    target = models.CharField(max_length=CHOICES_FIELD_MAX_LENGTH, choices=TARGETS)
    time_type = models.CharField(max_length=CHOICES_FIELD_MAX_LENGTH, choices=__TIME_TYPES)
    text = models.CharField(max_length=MAX_TEXT_FIELD_LENGTH, null=True, blank=True)
    datetime = models.DateTimeField()
    delta = models.DurationField(null=True, blank=True)
    is_sent = models.BooleanField(default=False)

    def send(self):
        if self.target == Notification.DASHBOARD_TARGET_SHORT:
            text = self.text
            if not text:
                text = Notification.DEFAULT_TEXT.format(task_name=self.task.name)
            Dashboard.objects.create(user=self.task.owner, text=text, reason=Dashboard.NOTIFICATION_REASON_SHORT)
        elif self.target == Notification.EMAIL_TARGET_SHORT:
            text = self.text
            if not text:
                text = Notification.DEFAULT_TEXT.format(task_name=self.task.name)
            from django.core.mail import send_mail
            from django.conf import settings
            email_from = settings.EMAIL_HOST_USER
            send_mail(Notification.EMAIL_SUBJECT, text, settings.EMAIL_HOST_USER, [self.task.owner.email])
        self.is_sent = True
        self.save()

    def update_copies(self):
        def subtract_dt(dt1, dt2):
            return relativedelta(years=dt1.year - dt2.year, months=dt1.month - dt2.month, days=dt1.day - dt2.day)
        delta = subtract_dt(self.task.end, self.datetime)
        for notification in self.copies.all():
            notification.delta = self.delta
            notification.text = self.text
            notification.time_type = self.time_type
            notification.target = self.target
            notification.datetime = notification.task.end - delta
            notification.save()

    def add_to_repeats(self):
        for task in Task.objects.filter(repeat__repeat__template_task=self.task):
            delta = task.end - self.task.end
            copied = Notification.objects.create(task=task,
                                                 datetime=self.datetime + delta,
                                                 target=self.target,
                                                 time_type=self.time_type,
                                                 delta=self.delta,
                                                 text=self.text,
                                                 copy_of=self)
            copied.save()

Remember/models/task.py
from datetime import datetime

from django.core.exceptions import ValidationError
from django.db import models, IntegrityError
from django.contrib.auth import models as auth_mod
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver

from .. import config
from .. import consts
from django.utils.translation import ugettext_lazy as _
from .dashboard import Dashboard


def priority_validator(value):
    if value < 0 or value > config.MAX_PRIORITY:
        raise ValidationError(
            _('%(value)d is not a valid priority. Expected in range 0,' + str(config.MAX_PRIORITY)),
            params={'value': value},
        )


def status_validator(value):
    if value < 0 or value > consts.MAX_STATUS:
        raise ValidationError(
            _('%(value)d is not a valid status. Expected in range 0,' + str(consts.MAX_STATUS)),
            params={'value': value},
        )


class Task(models.Model):
    DEFAULT_TIMELIMIT_TEXT = 'Task {name} ({description})has hit a time limit'
    RESULT_NOT_FINISHED = 'N'
    RESULT_SUCCESS = 'S'
    RESULT_FAILED = 'F'

    DEFAULT_RESULT = RESULT_SUCCESS
    RESULT_CHOICES = (
        (RESULT_NOT_FINISHED, 'Not finished yet'),
        (RESULT_FAILED, 'Failed'),
        (RESULT_SUCCESS, 'Success')
    )
    INITIAL_RESULT = RESULT_CHOICES[0][0]
    __DB_CHOICES_LEN = 2
    SCOPE_PRIVATE_SHORT = consts.SCOPE_PRIVATE[:__DB_CHOICES_LEN]
    SCOPE_PUBLIC_SHORT = consts.SCOPE_PUBLIC[:__DB_CHOICES_LEN]
    __scope_choices = (
        (SCOPE_PRIVATE_SHORT, consts.SCOPE_PRIVATE),
        (SCOPE_PUBLIC_SHORT, consts.SCOPE_PUBLIC)
    )
    __DEFAULT_SCOPE = config.DEFAULT_SCOPE[:__DB_CHOICES_LEN]

    owner = models.ForeignKey(auth_mod.User,
                              on_delete=models.CASCADE,
                              related_name='owned_tasks')
    assigned = models.ForeignKey(auth_mod.User,
                                 on_delete=models.SET_NULL,
                                 blank=True,
                                 null=True,
                                 related_name='assigned_tasks')
    name = models.CharField(max_length=config.TASK_MAX_NAME_LENGTH)
    description = models.TextField(max_length=config.MAX_TEXT_FIELD_LENGTH,
                                   blank=True,
                                   null=True)
    priority = models.IntegerField(validators=[priority_validator])
    status = models.IntegerField(validators=[status_validator],
                                 null=True)
    result = models.CharField(max_length=config.CHOICES_FIELD_MAX_LENGTH,
                              choices=RESULT_CHOICES,
                              default=RESULT_CHOICES[0][0])
    scope = models.CharField(max_length=config.CHOICES_FIELD_MAX_LENGTH,
                             choices=__scope_choices,
                             default=__DEFAULT_SCOPE)
    repeat = models.OneToOneField('TaskRepeatConnection',
                                  on_delete=models.CASCADE,
                                  blank=True,
                                  null=True,
                                  default=None)

    start = models.DateTimeField(null=True)
    start_message_sent = models.BooleanField(default=False)
    end = models.DateTimeField(null=True)

    def change_tags(self, tags):
        for tag in tags:
            try:
                Tag.objects.create(task=self, name=tag)
            except IntegrityError:
                pass
        Tag.objects.filter(~Q(name__in=tags), task=self).delete()

    def complete_task(self):
        queue = [self]
        changed = [self]
        while queue:
            task = queue.pop()
            for connection in task.received_connections.all():
                if connection.sender not in changed and connection.sender.result == Task.RESULT_NOT_FINISHED:
                    result = connection.commit_action()
                    if result:
                        queue.append(connection.sender)
                        changed.append(connection.sender)
        queue = [self]
        while queue:
            task = queue.pop()
            for connection in task.child_connection.all():
                if connection.sender.result == Task.RESULT_NOT_FINISHED:
                    connection.sender.result = self.result
                    connection.sender.status = consts.MAX_STATUS
                    connection.sender.save()
                    queue.append(connection.sender)

    def delete_actions(self):
        queue = [self]
        while queue:
            task = queue.pop()
            for connection in task.child_connection.all():
                queue.append(connection.sender)
            task.delete()

    def end_timelimit_hit(self):
        self.status = consts.MAX_STATUS
        self.result = Task.DEFAULT_RESULT
        self.save()
        text = Task.DEFAULT_TIMELIMIT_TEXT.format(name=self.name, description=self.description)
        Dashboard.objects.create(user=self.owner, text=text, reason=Dashboard.TIME_LIMIT_REASON_SHORT)
        self.complete_task()
        if self.repeat is not None:
            self.repeat.repeat.current_index += 1
            self.repeat.repeat.save()
            self.repeat.repeat.init_next_repeat()

    def update_repeats(self):
        for task in Task.objects.filter(repeat__repeat__template_task=self,
                                        repeat__rep_type=TaskRepeatConnection.NOT_CHANGED_REPEAT_TYPE):
            task.name = self.name
            task.description = self.description
            task.scope = self.scope
            task.status = self.status
            task.result = self.result
            task.assigned = self.assigned
            task.priority = self.priority
            task.save()

    def update_timelimit(self, user):
        # check exclusions
        if not Repeat.objects.filter(template_task=self).exists():
            return
        for connection in self.repeat_of.taskrepeatconnection_set.all():
            if connection.rep_type != TaskRepeatConnection.NOT_CHANGED_REPEAT_TYPE:
                new_index = self.repeat_of.check_date_belongs(self.end, connection.task.end.date())
                if new_index is not None:
                    connection.index = new_index
                    connection.save()
                else:
                    connection.delete()
        # get required copies count
        i = 0
        import pytz
        start = self.repeat_of.template_task.end
        while start.replace(tzinfo=pytz.UTC) < datetime.utcnow().replace(tzinfo=pytz.UTC):
            start += self.repeat_of.get_next_repeat(start)
            i += 1
        # create copies
        for index in range(i):
            if not TaskRepeatConnection.objects.filter(repeat=self.repeat_of, index=index).exists():
                from ..system import System
                System.copy_task(user, self.id, self.repeat_of, index)

    def __str__(self):
        return self.name


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(auth_mod.User, on_delete=models.CASCADE)
    text = models.CharField(max_length=config.MAX_TEXT_FIELD_LENGTH)
    time = models.DateTimeField()


def tag_len_validator(value):
    if len(value) < config.TAG_MIN_LENGTH:
        raise ValidationError(
            _('%(value)d is too short. Expected in length >=' + str(config.TAG_MIN_LENGTH)),
            params={'value': value},
        )


class Tag(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    name = models.CharField(max_length=config.TAG_MAX_LENGTH, validators=[tag_len_validator])

    class Meta:
        unique_together = (("task", "name"),)


class Log(models.Model):
    EVENT_CREATED = 'C'
    EVENT_EDITED = 'E'
    LOG_EVENTS = (
        (EVENT_CREATED, 'Created'),
        (EVENT_EDITED, 'Edited')
    )

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    event = models.CharField(max_length=config.CHOICES_FIELD_MAX_LENGTH, choices=LOG_EVENTS)
    time = models.DateTimeField()


@receiver(post_save, sender=Task)
def my_handler(sender, instance, created, **kwargs):
    if created:
        event = Log.EVENT_CREATED
    else:
        event = Log.EVENT_EDITED
    Log.objects.create(task=instance, event=event, time=datetime.now())


class SubtaskConnection(models.Model):
    # task.parent_connection.receiver.id

    sender = models.OneToOneField(Task,
                                  on_delete=models.CASCADE,
                                  related_name='parent_connection',
                                  primary_key=True)
    receiver = models.ForeignKey(Task,
                                 on_delete=models.CASCADE,
                                 related_name='child_connection')
    root = models.ForeignKey(Task,
                             on_delete=models.CASCADE,
                             related_name='root_connections',
                             null=True)
    depth = models.PositiveIntegerField(null=True)

    @staticmethod
    def get_root_and_depth(receiver):
        if SubtaskConnection.objects.filter(sender=receiver).exists():
            conn = SubtaskConnection.objects.get(sender=receiver)
            return conn.root, conn.depth + 1
        else:
            return receiver, 1


class TaskConnection(models.Model):
    TWT_TYPE_SHORT = 'TWT'
    FWT_TYPE_SHORT = 'FWT'
    TWF_TYPE_SHORT = 'TWF'
    FWF_TYPE_SHORT = 'FWF'
    INFO_TYPE_SHORT = 'INFO'

    TYPES = (
        (TWT_TYPE_SHORT, 'True when true'),
        (FWT_TYPE_SHORT, 'False when true'),
        (TWF_TYPE_SHORT, 'True when false'),
        (FWF_TYPE_SHORT, 'False when false'),
        (INFO_TYPE_SHORT, 'Info')
    )
    sender = models.ForeignKey(Task,
                               on_delete=models.CASCADE,
                               related_name='sent_connections')
    receiver = models.ForeignKey(Task,

Remember/templates/Remember/details/comments.html
<div class="container-fluid">
    {% for comment in task.comment_set.all %}
    <div class="row">
        <div class="col-9 offset-1">
            <div class="container-fluid" id="comment_container">
                <label style="font-size:22px">
                    {{ comment.text }}
                </label>
                <hr>
                <label style="font-size:12px">
                    {{ comment.time|date:"Y-m-d H:i" }} by {{ comment.user }}
                </label>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="row">
        <div class="col-9 offset-1">
            <form action="" method="post">
                {% csrf_token %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-10 my-1">
                            <input type="text" style="width:100%;" name="comment_text" id="add_comment_input">
                        </div>
                        <div class="col-2">
                            <div class="btn-group-vertical" style="width: 100%;">
                                <input class="btn btn-primary" style="width:100%;" type="submit" name="comment_add"
                                       value="Add">
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Remember/templates/Remember/details/connections.html
<div class="container-fluid">
    {% if task.sent_connections.all %}
        <div class="container-fluid">
            <div class="row">
                <label>Connected to:</label>
            </div>
            <div class="col offset-1">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Target</th>
                        <th scope="col">Type</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for connection in task.sent_connections.all %}
                            <tr>
                                <td>
                                    <label>
                                        <a href="{% url 'Remember:task_details' connection.receiver.id %}">
                                        {{ connection.receiver.name }}
                                        {% if connection.receiver.description %}
                                            ( {{ connection.receiver.description|truncatechars:40 }} )
                                        {% endif %}
                                        </a>
                                    </label>
                                </td>
                                <td>
                                    {{ connection.get_conn_type_display }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <label>Task isn't connected to anyone</label>
    {% endif %}

    <hr>

    {% if task.received_connections.all %}
        <div class="container-fluid">
            <div class="row">
                <label>Connected to it:</label>
            </div>
            <div class="col offset-1">
                 <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Target</th>
                        <th scope="col">Type</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for connection in task.received_connections.all %}
                            <tr>
                                <td>
                                    <label>
                                        <a href="{% url 'Remember:task_details' connection.sender.id %}">
                                        {{ connection.sender.name }}
                                        {% if connection.sender.description %}
                                            ( {{ connection.sender.description|truncatechars:40 }} )
                                        {% endif %}
                                        </a>
                                    </label>
                                </td>
                                <td>
                                    {{ connection.get_conn_type_display }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <label>Other tasks are not connected to this</label>
    {% endif %}
</div>

Remember/templates/Remember/details/log.html
<div class="container-fluid">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Time</th>
            <th scope="col">Event</th>
        </tr>
        </thead>
        <tbody>
        {% for log in task.log_set.all %}
            <tr>
                <td>{{ log.time|date:"Y-m-d H:i" }}</td>
                <td>{{ log.get_event_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

Remember/templates/Remember/details/main_info.html
<div class="container-fluid">
    <!-- description -->
    <div class="row">
        <div class="col-2">
            <label>Description:</label>
        </div>
        <div class="col">
            <label>
                {% if task.description %}
                {{ task.description }}
                {% else %}
                no description yet
                {% endif %}
            </label>
        </div>
    </div>
    <!-- tags -->
    <div class="row">
        <div class="col-2">
            <label>Tags:</label>
        </div>
        <div class="col">
            {% if task.tag_set.all %}
            {% for tag in task.tag_set.all %}
            <label id="tag_label">
                {{ tag.name }}
            </label>
            {% endfor %}
            {% else %}
            <label>
                No tags yet
            </label>
            {% endif %}
        </div>
    </div>
    <!-- assigned -->
    <div class="row">
        <div class="col-2">
            <label>Assigned to:</label>
        </div>
        <div class="col">
             <label>
                 {% if task.assigned %}
                 <em>{{ task.assigned.username }}</em>
                 {% else %}
                 Not yet
                 {% endif %}
             </label>
        </div>
    </div>
    <!-- status & result -->
    <div class="row">
        <div class="col-2">
            <label>
                {% if task.result != 'N' %}
                Result:
                {% else %}
                Status:
                {% endif %}
            </label>
        </div>
        <div class="col">
            <label>
                {% if task.result != 'N' %}
                {{ task.get_result_display }}
                {% else %}
                {{ task.status }}
                {% endif %}
            </label>
        </div>
    </div>
    <!-- scope -->
    <div class="row">
        <div class="col-2">
            <label>Scope:</label>
        </div>
        <div class="col">
             <label>{{ task.get_scope_display  }}</label>
        </div>
    </div>
    <!-- time limit -->
    <div class="row">
        <div class="col-2">
            <label>Time limit:</label>
        </div>
        <div class="col">
            {% if task.end %}
                {% if task.start %}
                    <label>from {{ task.start }} to </label>
                {% endif %}
                <label>{{ task.end }}</label>
            {% else %}
                <label>No timelimit</label>
            {% endif %}
        </div>
    </div>
</div>

Remember/templates/Remember/details/notifications.html
{% if task.notification_set.all %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Target</th>
            <th scope="col">Date</th>
            <th scope="col">Text</th>
        </tr>
        </thead>
        <tbody>
        {% for notification in task.notification_set.all %}
            <tr>
                <td>{{ notification.get_target_display }}</td>
                <td>{{ notification.datetime }}</td>
                <td>
                    {% if notification.text %}
                    {{ notification.text }}
                    {% else %}
                    No text provided
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <label>No notifications yet</label>
{% endif %}

Remember/templates/Remember/details/repeat_form.html
<form action="" method="post">
    {% csrf_token %}
    <tr>
        <td>{{ repeat.index }}</td>
        <td>{{ repeat.get_rep_type_display  }}</td>
        {% if repeat.rep_type != "D" %}
        <td>
            <input type="hidden" name="index" value="{{ repeat.index }}">
            <input type="number" min="0" max="100" name="status" value="{{ repeat.task.status }}">
            <select name="result">
                {% if repeat.task.result == "N" %}
                <option selected value="N">Not finished yet</option>
                {% else %}
                <option value="N">Not finished yet</option>
                {% endif %}
                {% if repeat.task.result == "S" %}
                <option selected value="S">Success</option>
                {% else %}
                <option value="S">Success</option>
                {% endif %}
                {% if repeat.task.result == "F" %}
                <option selected value="F">Failed</option>
                {% else %}
                <option value="F">Failed</option>
                {% endif %}
            </select>
            <input type="submit" name="repeat_save" value="save" class="btn btn-outline-primary">
        </td>
        {% else %}
        {% endif %}
    </tr>
</form>

Remember/templates/Remember/details/repeats.html
<div class="container-fluid">
    {% if task.repeat_of %}
        <div class="row">
            <label>{{ task.repeat_of.rule_human_readable }}</label>
        </div>
        <div class="row">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Index</th>
                    <th scope="col">Type</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for repeat in task.repeat_of.taskrepeatconnection_set.all %}
                    {% if repeat.index <= repeat.repeat.current_index %}
                        {% include 'Remember/details/repeat_form.html' %}
                    {% elif repeat.rep_type != "N" %}
                        {% include 'Remember/details/repeat_form.html' %}
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <label>Is not repeatable yet</label>
    {% endif %}
</div>

Remember/templates/Remember/details/subtasks.html
<div class="container-fluid">
    {% if task.parent_connection %}
        <label>Subtask for
            <a href="{% url 'Remember:task_details' task.parent_connection.receiver.id %}">
                {{ task.parent_connection.receiver.name }}
                {% if task.parent_connection.receiver.description %}
                    ( {{ task.parent_connection.receiver.description }} )
                {% endif %}
            </a>
        </label>
    {% else %}
        <label>Task is not subtask for anyone</label>
    {% endif %}
    <hr>
    {% if task.child_connection %}
        <div class="container-fluid">
            <div class="row">
                <label>Subtasks:</label>
            </div>
            <div class="col offset-1">
                {% for connection in task.child_connection.all %}
                    <label>
                        <a href="{% url 'Remember:task_details' connection.sender.id %}">
                            {{ connection.sender.name }}
                            {% if connection.sender.description %}
                                ( {{ connection.sender.description }} )
                            {% endif %}
                        </a>
                    </label>
                    <br>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <label>Task has no subtasks</label>
    {% endif %}
</div>