Remember/urls.py
from django.conf.urls import include, url

from .views import *
import django.conf.urls

app_name = 'Remember'
urlpatterns = [
    url(r'^hello$', foo, name='hello'), 
    url(r'^$', index, name='index'),
    url(r'^logout$', logout_view, name='logout'),
    url(r'^signup$', SignUpView.as_view(), name='signup'),
    url(r'^login', LoginView.as_view(), name='login'),
    url(r'^profile', ProfileView.as_view(), name='profile'),
    url('^calendar$', CalendarView.as_view(), name='calendar'),
    url('^dashboard$', dashboard, name='dashboard'),
    url('^task/', include([
        url('^new/$', TaskCreateView.as_view(), name='task_new'),
        url('(?P<task_id>\d+)/', include([
            url('^details/$', task_details, name='task_details'),
            url('^edit/', include([
                url('^$', TaskUpdateView.as_view(), name='task_edit'),
                url('^complex$', edit_task_complex, name='task_edit_complex'),
                url('^notification/', include([
                    url('(?P<notification_id>\d+)', NotificationUpdateView.as_view(), name='notification_edit'),
                    url('new$', NotificationCreateView.as_view(), name='notification_new')
                ])),
                url('repeat/', include([
                    url('create$', RepeatCreateView.as_view(), name='repeat_new'),
                    url('edit', RepeatUpdateView.as_view(), name='repeat_edit'),
                    url('add_exclusion', ExclusionCreateView.as_view(), name='exclusion_add')
                ])),
                url('^connection/', include([
                    url('subtask/(?P<user_username>.+)/edit', SubConnectionUpdateView.as_view(), name='subtask_edit'),
                    url('subtask/(?P<user_username>.+)$', SubConnectionCreateView.as_view(), name='subtask'),
                    url('create/(?P<user_username>[a-zA-Z0-9]+)$', ConnectionCreateView.as_view(), name='connection_new'),
                    url('create/(?P<user_username>.+)/(?P<receiver_id>\d+)', ConnectionUpdateView.as_view(),
                        name='connection_edit'),
                ])),
            ])),
        ])),
    ]))
]


django.conf.urls.handler404 = 'Remember.views.handler404'
django.conf.urls.handler500 = 'Remember.views.handler500'
django.conf.urls.handler403 = 'Remember.views.handler403'
django.conf.urls.handler400 = 'Remember.views.handler400'

TaskTracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import reverse
from django.views.generic import RedirectView

urlpatterns = [
    url(r'remember/', include('Remember.urls'), name='remember'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='remember/', permanent=False))
]

Remember/models/dashboard.py
import django.contrib.auth.models as auth_models
from django.db import models

from ..config import CHOICES_FIELD_MAX_LENGTH, MAX_TEXT_FIELD_LENGTH


class Dashboard(models.Model):
    NOTIFICATION_REASON_SHORT = 'N'
    ASSIGN_REASON_SHORT = 'A'
    TIME_LIMIT_REASON_SHORT = 'T'

    REASONS = (
        (NOTIFICATION_REASON_SHORT, 'Notification'),
        (ASSIGN_REASON_SHORT, 'Assign'),
        (TIME_LIMIT_REASON_SHORT, 'Time limit')
    )

    user = models.ForeignKey(auth_models.User, on_delete=models.CASCADE)
    text = models.CharField(max_length=MAX_TEXT_FIELD_LENGTH)
    reason = models.CharField(max_length=CHOICES_FIELD_MAX_LENGTH, choices=REASONS)
    datetime = models.DateTimeField(auto_now_add=True)

Remember/models/notification.py
from dateutil.relativedelta import relativedelta
from django.db import models

from .dashboard import Dashboard
from .task import Task
from .. import consts
from ..config import CHOICES_FIELD_MAX_LENGTH, MAX_TEXT_FIELD_LENGTH


class Notification(models.Model):
    EMAIL_SUBJECT = 'Remember! notification'
    __CHOICES_LENGTH = 1
    DEFAULT_TEXT = 'Task {task_name} hit the notification time.'
    EMAIL_TARGET_SHORT = consts.NOTIFICATION_EMAIL_TARGET[:__CHOICES_LENGTH]
    DASHBOARD_TARGET_SHORT = consts.NOTIFICATION_DASHBOARD_TARGET[:__CHOICES_LENGTH]
    TARGETS = (
        (EMAIL_TARGET_SHORT, consts.NOTIFICATION_EMAIL_TARGET),
        (DASHBOARD_TARGET_SHORT, consts.NOTIFICATION_DASHBOARD_TARGET)
    )
    ABSOLUTE_SHORT = consts.ABSOLUTE_TIME_TYPE[:__CHOICES_LENGTH]
    RELATIVE_SHORT = 'R'

    __TIME_TYPES = (
        (ABSOLUTE_SHORT, consts.ABSOLUTE_TIME_TYPE),
        (RELATIVE_SHORT, consts.RELATIVE_TIME_TYPE)
    )

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    copy_of = models.ForeignKey('Notification',
                                on_delete=models.CASCADE,
                                related_name='copies',
                                null=True)
    target = models.CharField(max_length=CHOICES_FIELD_MAX_LENGTH, choices=TARGETS)
    time_type = models.CharField(max_length=CHOICES_FIELD_MAX_LENGTH, choices=__TIME_TYPES)
    text = models.CharField(max_length=MAX_TEXT_FIELD_LENGTH, null=True, blank=True)
    datetime = models.DateTimeField()
    delta = models.DurationField(null=True, blank=True)
    is_sent = models.BooleanField(default=False)

    def send(self):
        if self.target == Notification.DASHBOARD_TARGET_SHORT:
            text = self.text
            if not text:
                text = Notification.DEFAULT_TEXT.format(task_name=self.task.name)
            Dashboard.objects.create(user=self.task.owner, text=text, reason=Dashboard.NOTIFICATION_REASON_SHORT)
        elif self.target == Notification.EMAIL_TARGET_SHORT:
            text = self.text
            if not text:
                text = Notification.DEFAULT_TEXT.format(task_name=self.task.name)
            from django.core.mail import send_mail
            from django.conf import settings
            email_from = settings.EMAIL_HOST_USER
            send_mail(Notification.EMAIL_SUBJECT, text, settings.EMAIL_HOST_USER, [self.task.owner.email])
        self.is_sent = True
        self.save()

    def update_copies(self):
        def subtract_dt(dt1, dt2):
            return relativedelta(years=dt1.year - dt2.year, months=dt1.month - dt2.month, days=dt1.day - dt2.day)
        delta = subtract_dt(self.task.end, self.datetime)
        for notification in self.copies.all():
            notification.delta = self.delta
            notification.text = self.text
            notification.time_type = self.time_type
            notification.target = self.target
            notification.datetime = notification.task.end - delta
            notification.save()

    def add_to_repeats(self):
        for task in Task.objects.filter(repeat__repeat__template_task=self.task):
            delta = task.end - self.task.end
            copied = Notification.objects.create(task=task,
                                                 datetime=self.datetime + delta,
                                                 target=self.target,
                                                 time_type=self.time_type,
                                                 delta=self.delta,
                                                 text=self.text,
                                                 copy_of=self)
            copied.save()

Remember/models/task.py
from datetime import datetime

from django.core.exceptions import ValidationError
from django.db import models, IntegrityError
from django.contrib.auth import models as auth_mod
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver

from .. import config
from .. import consts
from django.utils.translation import ugettext_lazy as _
from .dashboard import Dashboard


def priority_validator(value):
    if value < 0 or value > config.MAX_PRIORITY:
        raise ValidationError(
            _('%(value)d is not a valid priority. Expected in range 0,' + str(config.MAX_PRIORITY)),
            params={'value': value},
        )


def status_validator(value):
    if value < 0 or value > consts.MAX_STATUS:
        raise ValidationError(
            _('%(value)d is not a valid status. Expected in range 0,' + str(consts.MAX_STATUS)),
            params={'value': value},
        )


class Task(models.Model):
    DEFAULT_TIMELIMIT_TEXT = 'Task {name} ({description})has hit a time limit'
    RESULT_NOT_FINISHED = 'N'
    RESULT_SUCCESS = 'S'
    RESULT_FAILED = 'F'

    DEFAULT_RESULT = RESULT_SUCCESS
    RESULT_CHOICES = (
        (RESULT_NOT_FINISHED, 'Not finished yet'),
        (RESULT_FAILED, 'Failed'),
        (RESULT_SUCCESS, 'Success')
    )
    INITIAL_RESULT = RESULT_CHOICES[0][0]
    __DB_CHOICES_LEN = 2
    SCOPE_PRIVATE_SHORT = consts.SCOPE_PRIVATE[:__DB_CHOICES_LEN]
    SCOPE_PUBLIC_SHORT = consts.SCOPE_PUBLIC[:__DB_CHOICES_LEN]
    __scope_choices = (
        (SCOPE_PRIVATE_SHORT, consts.SCOPE_PRIVATE),
        (SCOPE_PUBLIC_SHORT, consts.SCOPE_PUBLIC)
    )
    __DEFAULT_SCOPE = config.DEFAULT_SCOPE[:__DB_CHOICES_LEN]

    owner = models.ForeignKey(auth_mod.User,
                              on_delete=models.CASCADE,
                              related_name='owned_tasks')
    assigned = models.ForeignKey(auth_mod.User,
                                 on_delete=models.SET_NULL,
                                 blank=True,
                                 null=True,
                                 related_name='assigned_tasks')
    name = models.CharField(max_length=config.TASK_MAX_NAME_LENGTH)
    description = models.TextField(max_length=config.MAX_TEXT_FIELD_LENGTH,
                                   blank=True,
                                   null=True)
    priority = models.IntegerField(validators=[priority_validator])
    status = models.IntegerField(validators=[status_validator],
                                 null=True)
    result = models.CharField(max_length=config.CHOICES_FIELD_MAX_LENGTH,
                              choices=RESULT_CHOICES,
                              default=RESULT_CHOICES[0][0])
    scope = models.CharField(max_length=config.CHOICES_FIELD_MAX_LENGTH,
                             choices=__scope_choices,
                             default=__DEFAULT_SCOPE)
    repeat = models.OneToOneField('TaskRepeatConnection',
                                  on_delete=models.CASCADE,
                                  blank=True,
                                  null=True,
                                  default=None)

    start = models.DateTimeField(null=True)
    start_message_sent = models.BooleanField(default=False)
    end = models.DateTimeField(null=True)

    def change_tags(self, tags):
        for tag in tags:
            try:
                Tag.objects.create(task=self, name=tag)
            except IntegrityError:
                pass
        Tag.objects.filter(~Q(name__in=tags), task=self).delete()

    def complete_task(self):
        queue = [self]
        changed = [self]
        while queue:
            task = queue.pop()
            for connection in task.received_connections.all():
                if connection.sender not in changed and connection.sender.result == Task.RESULT_NOT_FINISHED:
                    result = connection.commit_action()
                    if result:
                        queue.append(connection.sender)
                        changed.append(connection.sender)
        queue = [self]
        while queue:
            task = queue.pop()
            for connection in task.child_connection.all():
                if connection.sender.result == Task.RESULT_NOT_FINISHED:
                    connection.sender.result = self.result
                    connection.sender.status = consts.MAX_STATUS
                    connection.sender.save()
                    queue.append(connection.sender)

    def delete_actions(self):
        queue = [self]
        while queue:
            task = queue.pop()
            for connection in task.child_connection.all():
                queue.append(connection.sender)
            task.delete()

    def end_timelimit_hit(self):
        self.status = consts.MAX_STATUS
        self.result = Task.DEFAULT_RESULT
        self.save()
        text = Task.DEFAULT_TIMELIMIT_TEXT.format(name=self.name, description=self.description)
        Dashboard.objects.create(user=self.owner, text=text, reason=Dashboard.TIME_LIMIT_REASON_SHORT)
        self.complete_task()
        if self.repeat is not None:
            self.repeat.repeat.current_index += 1
            self.repeat.repeat.save()
            self.repeat.repeat.init_next_repeat()

    def update_repeats(self):
        for task in Task.objects.filter(repeat__repeat__template_task=self,
                                        repeat__rep_type=TaskRepeatConnection.NOT_CHANGED_REPEAT_TYPE):
            task.name = self.name
            task.description = self.description
            task.scope = self.scope
            task.status = self.status
            task.result = self.result
            task.assigned = self.assigned
            task.priority = self.priority
            task.save()

    def update_timelimit(self, user):
        # check exclusions
        if not Repeat.objects.filter(template_task=self).exists():
            return
        for connection in self.repeat_of.taskrepeatconnection_set.all():
            if connection.rep_type != TaskRepeatConnection.NOT_CHANGED_REPEAT_TYPE:
                new_index = self.repeat_of.check_date_belongs(self.end, connection.task.end.date())
                if new_index is not None:
                    connection.index = new_index
                    connection.save()
                else:
                    connection.delete()
        # get required copies count
        i = 0
        import pytz
        start = self.repeat_of.template_task.end
        while start.replace(tzinfo=pytz.UTC) < datetime.utcnow().replace(tzinfo=pytz.UTC):
            start += self.repeat_of.get_next_repeat(start)
            i += 1
        # create copies
        for index in range(i):
            if not TaskRepeatConnection.objects.filter(repeat=self.repeat_of, index=index).exists():
                from ..system import System
                System.copy_task(user, self.id, self.repeat_of, index)

    def __str__(self):
        return self.name


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(auth_mod.User, on_delete=models.CASCADE)
    text = models.CharField(max_length=config.MAX_TEXT_FIELD_LENGTH)
    time = models.DateTimeField()


def tag_len_validator(value):
    if len(value) < config.TAG_MIN_LENGTH:
        raise ValidationError(
            _('%(value)d is too short. Expected in length >=' + str(config.TAG_MIN_LENGTH)),
            params={'value': value},
        )


class Tag(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    name = models.CharField(max_length=config.TAG_MAX_LENGTH, validators=[tag_len_validator])

    class Meta:
        unique_together = (("task", "name"),)


class Log(models.Model):
    EVENT_CREATED = 'C'
    EVENT_EDITED = 'E'
    LOG_EVENTS = (
        (EVENT_CREATED, 'Created'),
        (EVENT_EDITED, 'Edited')
    )

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    event = models.CharField(max_length=config.CHOICES_FIELD_MAX_LENGTH, choices=LOG_EVENTS)
    time = models.DateTimeField()


@receiver(post_save, sender=Task)
def my_handler(sender, instance, created, **kwargs):
    if created:
        event = Log.EVENT_CREATED
    else:
        event = Log.EVENT_EDITED
    Log.objects.create(task=instance, event=event, time=datetime.now())


class SubtaskConnection(models.Model):
    # task.parent_connection.receiver.id

    sender = models.OneToOneField(Task,
                                  on_delete=models.CASCADE,
                                  related_name='parent_connection',
                                  primary_key=True)
    receiver = models.ForeignKey(Task,
                                 on_delete=models.CASCADE,
                                 related_name='child_connection')
    root = models.ForeignKey(Task,
                             on_delete=models.CASCADE,
                             related_name='root_connections',
                             null=True)
    depth = models.PositiveIntegerField(null=True)

    @staticmethod
    def get_root_and_depth(receiver):
        if SubtaskConnection.objects.filter(sender=receiver).exists():
            conn = SubtaskConnection.objects.get(sender=receiver)
            return conn.root, conn.depth + 1
        else:
            return receiver, 1


class TaskConnection(models.Model):
    TWT_TYPE_SHORT = 'TWT'
    FWT_TYPE_SHORT = 'FWT'
    TWF_TYPE_SHORT = 'TWF'
    FWF_TYPE_SHORT = 'FWF'
    INFO_TYPE_SHORT = 'INFO'

    TYPES = (
        (TWT_TYPE_SHORT, 'True when true'),
        (FWT_TYPE_SHORT, 'False when true'),
        (TWF_TYPE_SHORT, 'True when false'),
        (FWF_TYPE_SHORT, 'False when false'),
        (INFO_TYPE_SHORT, 'Info')
    )
    sender = models.ForeignKey(Task,
                               on_delete=models.CASCADE,
                               related_name='sent_connections')
    receiver = models.ForeignKey(Task,

Remember/templates/Remember/calendar.html
{% extends 'Remember/base.html' %}

{% block content %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'equinox/equinox.css' %}">
<!--<link rel="stylesheet" type="text/css" href="equinox/equinox.css">-->
<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.0.0/moment.min.js"></script>
<script type="text/javascript" src="{% static 'equinox/equinox.min.js' %}"></script>

<div class="event-calendar"></div>

{% if tasks %}
    <ul id="ul_tasks" class="tasks">
        {% for task in tasks %}
            <li class="task">
                <p class="task-name">{{ task.name }}</p>
                <p class="task-start">{{ task.start|date:"Y-m-d H:i" }}</p>
                <p class="task-end">{{ task.end|date:"Y-m-d H:i" }}</p>
                <p class="task-repeat">{{ task.repeat }}</p>
                <p class="task-details">{% url 'Remember:task_details' task.id %}</p>
            </li>
        {% endfor %}
    </ul>
{% endif %}

<script>
    let cal_tasks = []
    $('.tasks').each(function () {
        console.log("HERE");
        $(this).find('li').each(function () {
            task_name = $(this).find('.task-name').text();
            task_start = $(this).find('.task-start').text();
            task_end = $(this).find('.task-end').text();
            task_repeat = $(this).find('.task-repeat').text();
            task_details = $(this).find('.task-details').text();
            if(!task_start){
                task_start = task_end;
                console.log(task_start);
            }
            let my_color = '#0F0'
            if(task_repeat){
                my_color = '#F00';
            }
            cal_tasks.push({
                start: task_start,
                end: task_end,
                title: task_name,
                url: task_details,
                class: 'custom-class',
                color: my_color,
                data: {},
            });
        });
    });
    $('.event-calendar').equinox({
        events: cal_tasks,
    });

    document.getElementById("ul_tasks").style.display = "none";;
</script>

{% endblock %}

Remember/templates/Remember/connection_update_form.html
{% extends 'Remember/base.html' %}

{% block content %}

<div class="container">
    {{ form.non_field_errors }}
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-8 offset-2">
                <div class="container bg-light border rounded my-1">
                    {{ form.user_select }}
                    {{ form.task_id }}
                    {% for field in form.visible_fields %}
                    <div class="fieldWrapper">
                        <div class="container-fluid">
                            <div class="row my-2">
                                <div class="col-3 offset-1">
                                    {{ field.label_tag }}
                                </div>
                                <div class="col">
                                    {{ field }}
                                    {% if field.help_text %}
                                    <p class="help">{{ field.help_text|safe }}</p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row my-2">
                                <div class="col offset-5">
                                    {{ field.errors }}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col">
                <div class="btn-group-vertical" style="width: 100%;">
                    <input class="btn btn-primary" type="submit" name="save" value="Save">
                    <a class="btn btn-primary" href="{% url 'Remember:task_edit_complex' form.task_id.value %}">Back</a>
                </div>
            </div>
        </div>
        </form>
    </div>
</div>

{% endblock %}

Remember/templates/Remember/dashboard.html
{% extends 'Remember/base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-9">
            {% if dashboard %}
                {% for record in dashboard %}
                    {% include 'Remember/dashboard_record.html' %}
                {% endfor %}
            {% else %}
                <h1>No records</h1>
            {% endif %}
        </div>
        <div class="col">
            <div class="container-fluid bg-light sticky-top border rounded my-1 py-2">
                <form action="{% url 'Remember:dashboard' %}" method="post">
                    {% csrf_token %}
                    <div class="btn-group-vertical" style="width: 100%;">
                        <a class="btn btn-primary my-2" href="{% url 'Remember:index' %}">Back</a>
                        <input class="btn btn-outline-primary my-2" type="submit" name="records_clear_all" value="Clear all">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Remember/templates/Remember/notification_short.html
<div class="container bg-light border rounded my-1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Remember/task_list_styles.css' %} ">
    <div class="row">
        <div class="col my-2">
            <h5>
                {{ notification.get_target_display }}, on {{ notification.datetime }}
            </h5>
            {% if notification.text %}
                <br>
                {{ notification.text|truncatechars:100 }}
            {% else %}
                <br>
                No text provided
            {% endif %}
        </div>
        <div class="col-3">
            <div class="container-fluid">
                <form action="{% url 'Remember:task_edit_complex' notification.task.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="notification_id" value="{{ notification.id }}">
                    <div class="btn-group-vertical py-2" style="width: 100%;">
                        <input class="btn btn-primary" type="submit" name="notif_edit" value="edit">
                        <input class="btn btn-primary" type="submit" name="notif_delete" value="delete">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Remember/templates/Remember/task_complex_notifications.html
<div class="container-fluid bg-light border rounded my-1 py-2">
    <div class="col-8">
        <h3>Notifications:</h3>
    </div>
    {% if task.notification_set.all %}
    <div class="row">
        <div class="col offset">
            <table class="table table-striped border ">
                <thead>
                <tr>
                    <th scope="col">Target</th>
                    <th scope="col">Date & time</th>
                    <th scope="col">Text</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for notification in task.notification_set.all %}
                <form action="{% url 'Remember:task_edit_complex' notification.task.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="notification_id" value="{{ notification.id }}">
                    <tr>
                        <td>{{ notification.get_target_display }}</td>
                        <td>{{ notification.datetime }}</td>
                        <td>
                            {% if notification.text %}
                            {{ notification.text|truncatechars:20 }}
                            {% else %}
                            No text provided
                            {% endif %}
                        </td>
                        <td>
                            <input class="btn btn-outline-primary" type="submit" name="notif_edit" value="edit">
                            <input class="btn btn-outline-danger" type="submit" name="notif_delete"  value="delete">
                        </td>
                    </tr>
                </form>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% else %}
        <h5>No notifications yet</h5>
    {% endif %}
    <div class="row">
        <div class="col offset">
            <h5>
                <a href="{% url 'Remember:notification_new' task.id %}">Add new</a>
            </h5>
        </div>
    </div>
</div>

Remember/templates/Remember/task_list.html
{% extends "Remember/base.html" %}
{% load static %}

{% block content %}

<!--<link rel="stylesheet" type="text/css" href="{% static 'polls/mycss.css' %} ">-->
<!--<script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>-->
<!--<script type="text/javascript" src="{% static 'Remember/tags.js' %} "></script>-->
<!--<link rel="script" href="{% static 'Remember/tags.js' %} "/>-->
<div class="container">
    <div class="row">
        <!-- List of tasks -->
        <div class="col-9">
            {% for task in tasks %}
                {% include "Remember/task_short_template.html" %}
            {% endfor %}
        </div>

        <!-- Side menu -->
        <div class="col-3">
            <div class="container-fluid bg-light sticky-top border rounded my-1 py-2">
                <form action="{% url 'Remember:index' %}" method="get">
                    {% csrf_token %}
                    <label for="tags">Tags: </label>
                    <input id="tags" type="text" name="tags" value="{{ tags }}">
                    <label for="task_name">Name: </label>
                    <input id="task_name" type="text" name="task_name" value="{{ task_name }}">
                    <div class="container-fluid">
                        <div class="btn-group-vertical" style="width: 100%;">
                            <input class="btn btn-outline-primary my-2" type="submit" value="Search" name="not_finished">
                            <input class="btn btn-outline-primary my-2" type="submit" value="Search finished" name="finished">
                        </div>
                    </div>
                </form>
            </div>
            <div class="container-fluid bg-light sticky-top border rounded my-1 py-2">
                <div class="btn-group-vertical" style="width: 100%;">
                    <a class="btn btn-primary" href="{% url 'Remember:task_new' %}">New task</a>
                </div>
            </div>
        </div>
      </div>
</div>

{% endblock content %}

Remember/templates/Remember/task_short_template.html
<div class="container bg-light border rounded my-1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Remember/task_list_styles.css' %} ">
    <div class="row">
        <div class="col">
            <h5>
                <!-- priority color -->
                <a class="details" id="details_link" href="{% url 'Remember:task_details' task.id %}">
                    {{ task.name }}
                </a>,
                {% if task.priority == 0 %}
                    <label id="priority0">priority: {{ task.priority }}</label>
                {% endif %}
                {% if task.priority == 1 %}
                    <label id="priority1">priority: {{ task.priority }}</label>
                {% endif %}
                {% if task.priority == 2 %}
                    <label id="priority2">priority: {{ task.priority }}</label>
                {% endif %}
                {% if task.priority == 3 %}
                    <label id="priority3">priority: {{ task.priority }}</label>
                {% endif %}
                {% if task.priority == 4 %}
                    <label id="priority4">priority: {{ task.priority }}</label>
                {% endif %}
                {% if task.priority == 5 %}
                    <label id="priority5">priority: {{ task.priority }}</label>
                {% endif %}
            </h5>

            {% if task.owner != user %}
            <h6 style="color:#c2a818;">Owned by {{ task.owner.username }}</h6>
            {% endif %}

            {% if task.repeat_of %}
                <h6>{{ task.repeat_of.rule_human_readable }}</h6>
                <h6>Next repeat - number {{ task.repeat_of.current_index }}, type
                    {% for rep in task.repeat_of.taskrepeatconnection_set.all %}
                        {% if rep.index == task.repeat_of.current_index %}
                            {{ rep.get_rep_type_display }}
                        {% endif %}
                    {% endfor %}
                </h6>
            {% endif %}

            {% for tag in task.tag_set.all %}
                <label id="tag_label">
                    {{ tag.name }}
                </label>
            {% endfor %}
            {% if task.tag_set.count %}
                <br>
            {% endif %}

            {% if task.description  %}
                {{ task.description  }}
                <br>
            {% endif %}
            Id:
            <label style="font-size:8pt">
                {{ task.id }}
            </label>
            {% if task.assigned %}
                <br>
                Assigned to: {{ task.assigned }}
            {% endif %}

            <br>
            {% if task.result %}
                Result: {{ task.get_result_display }}
            {% else %}
                Status: {{ task.status }}
            {% endif %}
        </div>
        <div class="col-2">
            <div class="container-fluid">
                <form action="{% url 'Remember:index' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="task_id" value="{{ task.id }}">
                    <div class="btn-group-vertical py-2" style="width: 100%;">
                        <input class="btn btn-outline-primary" type="submit" name="edit" value="edit">
                        {% if task.owner == user %}
                        <input class="btn btn-outline-danger" type="submit" name="delete" value="delete">
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>